project:
  type: website

website:
  title: "Ecological Modelling with R"
  description: "An open educational project in ecological modelling, statistics and reproducible data analysis."
  
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true